### ISSUE TITLE
Boilerplate Initialization

### ISSUE THREAD

**Issue by TommyPurba** [TommyPurba/Infinitum#1]

**Comment by TommyPurba** [comment]
oke bos, i will set up all

**Comment by TommyPurba** [comment]
bos i already create the boilerplate

**Comment by indrazm** [comment]
This Boilerplate should be ready with folder structure. such as components, lib, styles, and so. 
Please fix.

**Comment by TommyPurba** [comment]
oke mr. indra

**Comment by TommyPurba** [comment]
hello guys 
can you check again about the folder i just add
if already appear can you give renspone emoji
